### ISSUE TITLE
What's the use case for this? Are there massive compatibility issues?

### ISSUE THREAD

**Issue by codepo8** [sindresorhus/chakra-nerp#1]
This, in essence, is like browser sniffing and blocking out people from using a newer engine than V8 for their scripts.
It's fine if your code is reliant on V8's special features, but isn't that a step back? What does the Chakra engine do differently that sparked this script? Maybe it can be fixed. I'd rather not see blocking of options on the server or client side. More than one engine is a good thing - it keeps our code more future-proof.

**Comment by sindresorhus** [comment]
https://twitter.com/sindresorhus/status/606144577645461505
